### ISSUE TITLE
Can't find variable: pug

### ISSUE THREAD

**Issue by jhessin** [pugjs/babel-plugin-transform-react-pug#10]
I have been using Pug with React-native and it has worked well thus far. However whenever I try using interpolation I get the following error screen: 
![simulator screen shot jul 23 2017 9 41 50 pm](https://user-images.githubusercontent.com/6241466/28507677-f9132790-6ff1-11e7-812d-5ee0b264afe6.png)
The only thing I need interpolation for is fat arrow functions (for onClick or onChangeText props). I have been able to work around this by creating external fat arrow methods and passing those, but doing that for every single time I need to update a text field can be a pain.
Here are my .babelrc and package.json:

.babelrc
`
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        "transform-react-pug",
        "transform-react-jsx"
      ]
    }
  }
}
`
package.json
`
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-plugin-transform-react-pug": "^3.1.8",
    "eslint-config-rallycoding": "^3.2.0",
    "eslint-plugin-pug": "^1.1.0",
    "jest-expo": "~18.0.0",
    "react-native-scripts": "0.0.50",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^18.0.3",
    "firebase": "^4.1.3",
    "native-base": "2.1.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
  }
}
`

**Comment by ljbc1994** [comment]
Hi, this is because the latest update to the plugin (which supports interpolation) isn't in the npm package. 

@ForbesLindesay: Not sure whether there are more updates to come before pushing `3.1.9`?

**Comment by jhessin** [comment]
so how do I do conditional rendering?

Do I need to create a separate component just for this?

**Comment by ForbesLindesay** [comment]
The latest release should support interpolation.  For what it's worth, you can just use pug without interpolation.

This should work fine:

```js
function MyComponent(props) {
  return pug`button(onClick=() => props.onClick('whatever'))`;
}
```
