### ISSUE TITLE
style jsx always affects global.

### ISSUE THREAD

**Issue by pruge** [pugjs/babel-plugin-transform-react-pug#100]
I am performing the following example.
https://nextjs.org/learn/basics/styling-components/no-effect-for-nested-components

The expected state is as follows.
![alt image](https://cloud.githubusercontent.com/assets/50838/25552972/6becac5c-2c5c-11e7-9fce-61cdc207a10d.png)

But in reality it looks like this:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/5827473/58450692-e8836900-814a-11e9-95f2-08f904c0ed43.png">

The example works fine.
https://github.com/zeit/next-learn-demo/tree/master/7-styling-components

But if you put .babelrc here, style affects global.
```
{
  "plugins": [
    "transform-react-pug",
    "transform-react-jsx",
    [
      "transform-jsx-classname-components",
      {
        "objects": [
          "React"
        ]
      }
    ]
  ]
}
```

Is there a way to enable scope style?

**Comment by ezhlobo** [comment]
@pruge sorry for the delay. I'll take a closer look at examples soon and will be able to discuss the things.

**Comment by ezhlobo** [comment]
@pruge I see that you use Next and you try to customize babel config. According to their documentation, when you add own `.babelrc` file, you must include Next's stuff there (including jsx-styled).

https://nextjs.org/docs#customizing-babel-config

So in your case, simply modify your `.babelrc` file:

```diff
  {
+   "presets": ["next/babel"],
    "plugins": [
      "transform-react-pug",
      "transform-react-jsx",
      [
        "transform-jsx-classname-components",
        {
          "objects": [
            "React"
          ]
        }
      ]
    ]
  }
```

If you continue experiencing the issue, will be really helpful if you provide your repository with reproduced issue.

**Comment by pruge** [comment]
thank you very much
