### ISSUE TITLE
Interpolated Tag

### ISSUE THREAD

**Issue by cihanzenginff** [pugjs/babel-plugin-transform-react-pug#107]
Hello, i'm using some validation plugin. 

and want to show message like that in jsx:

` {this.validator.message("title", this.state.title, "required|alpha")}`

i tried like that: 

` #{this.validator.message("title", this.state.title, "required|alpha")}`

but getting error: **Error: InterpolatedTag is not yet supported**

it's mean i can't use it not yet ?

**Comment by ForbesLindesay** [comment]
If `this.validator.message` returns a component:

```pug
- const Message = this.validator.message("title", this.state.title, "required|alpha");
Message
```

If `this.validator.message` returns a jsx element or string:

```pug
= this.validator.message("title", this.state.title, "required|alpha");
```

**Comment by cihanzenginff** [comment]
worked perfectly thanks
