### ISSUE TITLE
Component Names with Period?

### ISSUE THREAD

**Issue by zsteinkamp** [pugjs/babel-plugin-transform-react-pug#13]
How should we use pug markup for React components that have a period in the name? For example, React-Bootstrap (https://react-bootstrap.github.io/components.html#navigation) has many components named like "Tab.Content" or "Tab.Pane". 

When writing a the pug markup to use these components like this:
    
    pug`Tab.Content foo`

it is transpiled to:

    <Tab className="Content">foo</Tab>

when it should actually become:

    <Tab.Content>foo</Tab.Content>

Is there a good workaround? Thanks!

**Comment by ljbc1994** [comment]
Hi,

This is because of how class names are defined in Pug. To use components like `Tab.Content`, you can simply do the following: 

```js
const TabContent = Tab.Content;

pug`
  TabContent foo
`
```

Thanks
