### ISSUE TITLE
Add integration with eslint-plugin-react

### ISSUE THREAD

**Issue by ezhlobo** [pugjs/babel-plugin-transform-react-pug#14]
Hey guys, 

I started the project which kills my pain in using `eslint-plugin-react` and `babel-plugin-transform-react-pug` together: [eslint-plugin-react-pug](https://github.com/ezhlobo/eslint-plugin-react-pug).

I see many duplicates of issue like [#7 ('pug' is not defined no-undef)](#7), so I think it will be reasonable to mention `eslint-plugin-react-pug` in README. What do you think? 

**Pros:** everyone will easy know how to integrate this babel plugin with commonly used `eslint-plugin-react`.

**Cons:** `eslint-plugin-react-pug` is not tested enough on production.

**Comment by ForbesLindesay** [comment]
If you send a pull request that adds a brief description/explanation of this, I'd be happy to merge.

**Comment by ezhlobo** [comment]
@ForbesLindesay thank you. Started a PR #17
