### ISSUE TITLE
prop spreading (support attribute blocks)

### ISSUE THREAD

**Issue by p-98** [pugjs/babel-plugin-transform-react-pug#148]
I am trying to translate jsx with prop spreading to pug
```jsx
<div {...attributes} />
```

The only possibility I was able to come up with was
```pug
div&attributes(attributes)
```

Unfortunately this currently throws `Attribute blocks are not yet supported in react-pug`.

It would be awesome to see this feature supported. Or is there any other solution?

**Comment by ezhlobo** [comment]
@p-98 hey, have you tried `div(...attributes)`?

It works different ways, you can play here:
https://react.pugjs.org/repl#%7B%22code%22:%22ZXhwb3J0IGNvbnN0IFJlYWN0Q29tcG9uZW50ID0gcHJvcHMgPT4gcHVnYAogIGRpdiguLi5wcm9wcy5hdHR0cmlidXRlcykKICAKICBkaXYoLi4uYXR0cmlidXRlcykKYA==%22%7D

<img width="1021" alt="Screenshot 2021-11-19 at 18 21 09" src="https://user-images.githubusercontent.com/974552/142647009-6597da3d-7798-4efb-b3d3-cf0001b5ca1e.png">

**Comment by p-98** [comment]
@ezhlobo thanks for the clue. Seems like I missed it.

Since this syntax makes attribute blocks obsolete, I will close this issue.
