### ISSUE TITLE
Can I keep pug template in separate file?

### ISSUE THREAD

**Issue by mars-abd** [pugjs/babel-plugin-transform-react-pug#19]
Like this:

```
MyComponent/
    MyComponent.pug
    MyComponent.styl
    MyComponent.js
```

MyComponent.pug:
```
div(class=`${styles.container}`)
    p
        = this.state.text
```

MyComponent.js:
```
import React from 'react';
import styles from './MyComponent.styl';
import template from './MyComponent.pug'; // raw text loader

class MyComponent extends React.Component {
  render() {
    return pug`${template}`;
  }
}

**Comment by ezhlobo** [comment]
@mars-abd you can't (at least now).

It's also not planned for near future: https://github.com/pugjs/babel-plugin-transform-react-pug/issues/15

**Comment by mars-abd** [comment]
Sorry, it is duplicated issue

**Comment by SilencerWeb** [comment]
@mars-abd you can use this plugin https://github.com/bluewings/pug-as-jsx-loader/blob/master/README.md#import-pug-template

**Comment by ezhlobo** [comment]
Let's close this issue, since it's a duplicate. We can continue working on it, or just discuss it, within #15.

//CC @ForbesLindesay

**Comment by ForbesLindesay** [comment]
@ezhlobo you should have permission to close issues yourself if you want to.  I agree that we should close this issue as a duplicate though :)

**Comment by ezhlobo** [comment]
@ForbesLindesay I actually don't have any permission here

**Comment by ForbesLindesay** [comment]
Ooops, it looks like I created a `react-pug` team, and added you to it, but forgot to add the repository. Should be fixed now :)
