### ISSUE TITLE
How to insert a non-breaking space?

### ISSUE THREAD

**Issue by ezhlobo** [pugjs/babel-plugin-transform-react-pug#21]
It's not a bug or issue, probably, just a question.

My task is to make a text inside a template better by inserting `&nbsp;` and other symbols.

```jsx
pug`
  p Hello,&nbsp;World!
`
```

It outputs `Hello,&nbsp;World!` in browser but expected behavior is to have a real space. Could you help me to leverage this?

**Comment by brayhoward** [comment]
I think your no-break-space entity just needs spaces around it.
```
pug`
  p Hello, &nbsp; World!
`
```

If not try passing it as a string w/ the unicode number 
```
pug`
  p #{`Hello, ${String.fromCharCode(160)} World!`}
  // or 
  p ${"Hello, \u00A0 World!"}
`
```
And if all else fails
```
pug`
  p dangerouslySetInnerHTML={__html: 'First &nbsp; Second'}
`
```
Be careful generating html like that though. (https://reactjs.org/docs/dom-elements.html)[You can read more about it here]

**Comment by ezhlobo** [comment]
@brayhoward thank you for the answer. I was inspired by your suggestions and found this solution:

```jsx
pug`
  p= 'Hello,\u00A0World'
`
```

But why `&nbsp;` does not work in general? React supports it by default, but it's not available for us through react-pug...

PS. Why do you add spaces around the non-breaking space? I can't imagine a case for this...

**Comment by ezhlobo** [comment]
I investigated how it works internally (I mean this package and babel plugins) and realized, that it's definitely a problem in babel. They transform `&nbsp;` to `\u00A0` (actually to `\xA0`) during parsing phase if it's inside `JSXText`.

This message is just for your information. We still need to figure out the best way to do it for this plugin.

**Comment by ezhlobo** [comment]
It works from [the 5th version](https://github.com/pugjs/babel-plugin-transform-react-pug/releases/tag/5.0.0).
