### ISSUE TITLE
Supporting CSS modules: optional attribute name instead of className

### ISSUE THREAD

**Issue by ezhlobo** [pugjs/babel-plugin-transform-react-pug#27]
Some popular tools for integrating CSS modules with react relies on different attribute for class names. For example '[react-css-modules](https://github.com/gajus/react-css-modules)' expects `styleName`.

This
```jsx
<div styleName="class"></div>
```

Will be converted into this
```jsx
<div className="[context]__class__[hash]"></div>
```

So it would be good to add an option for this plugin to allow using different attribute names instead of 'className' always.

**Comment by ForbesLindesay** [comment]
I think this is probably still fairly usable as it is.

**Comment by ezhlobo** [comment]
This is done in v7.0.0. Need to improve documentation to make it easier to use.
