### ISSUE TITLE
iteration with conditional - must specify key error

### ISSUE THREAD

**Issue by leviwheatcroft** [pugjs/babel-plugin-transform-react-pug#28]
For example...

```
const contact = {
  name: 'Levi',
  someEmptyField: '',
}
return pug`
  div
    each value, key in contact
      if value
        p(key=key)= value
`
```

Throws `You must specify a key for the first item in any loops.`

As a workaround you can trim the empty values before you render the pug, so you don't need the conditional.

**Comment by ForbesLindesay** [comment]
#35 is tracking approximately the same issue. I'm going to close this issue as that one has more detail on my current thinking.
