### ISSUE TITLE
Expected "hash" to be an array because it is passed to each

### ISSUE THREAD

**Issue by leviwheatcroft** [pugjs/babel-plugin-transform-react-pug#29]
`each value, key in hash` throws `Expected "hash" to be an array because it is passed to each` if hash is an object.

It's usually possible to iterate over objects with each right? Says so in [the docs](https://pugjs.org/language/iteration.html)

**Comment by ezhlobo** [comment]
@leviwheatcroft it looks like a good thing to do. For now all loops are transpiled into `for` statements, but we can move it to `for-in` statements that support iterating over both arrays and objects.

I would like to address this, but need reaction from code maintainers.

**Comment by ForbesLindesay** [comment]
To work exactly like `each` in pug requires you to duplicate all code within the `each` block and switch at runtime between the array implementation and the object implementation.  This is hugely inefficient, and may eventually be deprecated/removed in pug (although not any time soon). It's also fairly rarely used in my experience.  For that reason, I decided that `each` in react-pug should only support arrays. You can always do:

```js
each key in Object.keys(hash)
  - const value = hash[key];
```
