### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by stevenxxiu** [pugjs/babel-plugin-transform-react-pug#30]
Babel 7 uses `require('@babel/core');` now, substituting that in the source appears to work.

A temporary fix now is to install `babel-core^7.0.0-bridge.0`.

**Comment by ForbesLindesay** [comment]
If the babel team publish a guide for plugin authors to migrate, we can add support for babel 7.  Failing that, once babel 7 is fully released, we could upgrade this library to babel 7 as a breaking change.  At the moment, we still need to support babel 6.

**Comment by ezhlobo** [comment]
@shirohana @stevenxxiu @jasperandrew we now officially support babel@7 starting from 7.0.0 version of this plugin.
