### ISSUE TITLE
 'pug' is not defined  no-undef

### ISSUE THREAD

**Issue by succulen-plants** [pugjs/babel-plugin-transform-react-pug#31]
class App extends React.Component {

  render() {
    return pug`
      div
        h1 My Component
        p This is my component using pug.
    `;
  }
}

export default App;

**Comment by ezhlobo** [comment]
@succulen-plants are you talking about error message from 'eslint'? There's a duplicate with one possible solution: #7.

The easiest way to handle this (IMO) is to add [eslint-plugin-react-pug](https://github.com/ezhlobo/eslint-plugin-react-pug) to your project.

**Comment by saqibarfeen** [comment]
https://stackoverflow.com/questions/56513346/how-to-use-pug-templating-engine-with-reactjs
