### ISSUE TITLE
object interpolation / casting / toString method.

### ISSUE THREAD

**Issue by leviwheatcroft** [pugjs/babel-plugin-transform-react-pug#32]
Lots of libraries return structures which rely on `toString` being used to interpolate them. For example...

```
import truncate from 'lodash'

const result = truncate('long string', {length:7})
...
render() {
  return pug`p= result`
}
```
You'd expect the above to render as `<p>long...</p>`, however lodash returns a chainable wrapper which is interpolated by this module as an empty string so you get `<p></p>`. you need to explicitly call `toString()` as in `return pug'p= result.toString()'`

The expected behaviour would be to call `toString` when rendering objects.

**Comment by ForbesLindesay** [comment]
This is an issue with React. It’s not specific to pug. It’s also better resolved by using the built in methods instead of lodash.
