### ISSUE TITLE
eslint error no-undef for looping variable

### ISSUE THREAD

**Issue by artificis** [pugjs/babel-plugin-transform-react-pug#38]
With regular React JSX syntax, I write like this:

```jsx
{Object.values(children).map(child => (
  <Tab
    key={child.id}
  >
    <ChildDetails child={child} />
  </Tab>
))}
```

With pug syntax, I write like this:

```pug
each child, i in Object.values(children)
  Tab(
    key=i
  )
    ChildDetails(child=child)
```

For me, pug syntax looks better in terms of legibility, but I get eslint error `no-undef` for iterator variable (`child`).

For now, I should disable eslint temporarily using `/* eslint-disable no-undef */` right before `return` statement in `render` function.

Can we make it pass eslint without this extra line of disabling eslint rule?

**UPDATE**: This is intermittent - it happens sometimes and doesn't happen other times.

**Comment by ForbesLindesay** [comment]
There are several other issues and even some docs about configuring eslint.

**Comment by artificis** [comment]
@ForbesLindesay Can you give me more specific information (e.g., link)? I already tried search but could not find - that's why I opened this issue here.

**Comment by artificis** [comment]
Perhaps I was not clear enough in my description. I'm getting `no-undef` eslint error for looping variable (not for `pug` indicator).

**Comment by ForbesLindesay** [comment]
Ah, you shouldn't get that. Are you linting the code before compiling, or after? Are you using eslint-plugin-react-pug? I wonder if it could be a bug in https://github.com/ezhlobo/pug-uses-variables (If so, you could try and narrow it down to a test case and open an issue there)

**Comment by artificis** [comment]
Yes, I'm using eslint-plugin-react-pug. Not sure if the linting occurs before/after compilation. I don't use pug-uses-variable (and don't know how to use that).

**Comment by artificis** [comment]
Here are my dot files.

`.babelrc`
```json
{
  "presets": [
    "react-app"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "transform-react-pug"
  ]
}
```

`.eslintrc`
```json
{
  "extends": ["airbnb-base", "plugin:react-pug/all", "prettier"],
  "plugins": ["prettier", "react-pug"],
  "env": {
    "browser": true
  },
  "rules": {
    "prettier/prettier": [
      "error",
      {
        "singleQuote": true
      }
    ],
    "class-methods-use-this": "off"
  },
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": {
          "resolve": {
            "modules": ["src"]
          }
        }
      }
    }
  }
}
```

**Comment by ForbesLindesay** [comment]
@ezhlobo do you have any suggestions here?

**Comment by ezhlobo** [comment]
Give me few hours to reproduce that

//CC @artificis @ForbesLindesay

**Comment by ezhlobo** [comment]
@artificis 

>This is intermittent - it happens sometimes and doesn't happen other times.

This makes my investigation almost impossible. I was not able to reproduce such behavior, and I have no idea how it can happen.

It would be great if you could set up a sample project with the same behavior, so I'll be able to debug.

PS. What do you think about creating a separate issue for this in [ezhlobo/eslint-plugin-react-pug](https://github.com/ezhlobo/eslint-plugin-react-pug), because it's more likely related to prettier and eslint than to this babel-plugin.

**Comment by artificis** [comment]
Will do
