### ISSUE TITLE
Is it possible to set the docytype?

### ISSUE THREAD

**Issue by weotch** [pugjs/babel-plugin-transform-react-pug#40]
Is there a way to set the doctype globally?

**Comment by ForbesLindesay** [comment]
The doctype shouldn't make any difference in react-pug

**Comment by weotch** [comment]
It does for interpretation of attributes.  Like whether `video(autoplay)` becomes `<video autoplay>` or `<video autoplay="autoplay">`.  If I want the former, is there a way outside of `doctype` to tell Pug how to treat the attribute?

**Comment by ForbesLindesay** [comment]
If you're actually using this library, `video(autoplay)` probably doesn't work yet (see #33).  If you do `video(autoplay=true)` that will be equivalent to the jsx code `<video autoplay={true} />`. There are other implementations of pug -> jsx, so it's possible you're using one of those.

**Comment by weotch** [comment]
I was evaulating the library to see if it would work for our project.  You're right, I addn't tried that specific example.

**Comment by ezhlobo** [comment]
@weotch hey, PR #33 was merged. Could you re-check, does everything work well for you?
