### ISSUE TITLE
How to use this plugin with create-react-app repo?

### ISSUE THREAD

**Issue by morwin10** [pugjs/babel-plugin-transform-react-pug#41]
I tried to do that but I get `'pug' is not defined  no-undef`

I copied these lines to `package.json` like that

```
"babel": {
  "plugins": [
    "transform-react-pug",
    "transform-react-jsx"
  ]
}
```

**Comment by letorruella** [comment]
Having the same problem, I am trying to implement without having to eject.

**Comment by ForbesLindesay** [comment]
@letorruella is correct

**Comment by ezhlobo** [comment]
@morwin10 there are few other options, like [react-app-rewired](https://github.com/timarney/react-app-rewired#1-injectbabelplugin).

Personally I use [module-alias](https://www.npmjs.com/package/module-alias) package and modify webpack config to allow `.babelrc` file in root directory. Then I modify all babel configurations as I want.

//CC @letorruella
