### ISSUE TITLE
Improvement: if else in atrribute

### ISSUE THREAD

**Issue by PhmNgocNghia** [pugjs/babel-plugin-transform-react-pug#53]
Can we have if else in attribute. like this : 
`a(
    className=if(foo===bar) foo else bar
)` 

Transpile into : 
`<a href={foo===bar? 'foo' : 'bar'}` />

**Comment by ezhlobo** [comment]
@PhmNgocNghia is using of ternary operator enough for you? Like:

```pug
a(className=foo === bar ? foo : bar)
```

It works currently, have you tried?

**Comment by ForbesLindesay** [comment]
Yes, pug supports arbitrary js expressions for attribute values just like jsx does, so just use a ternary.
