### ISSUE TITLE
Pug tag disrespects module definition?

### ISSUE THREAD

**Issue by stevefan1999** [pugjs/babel-plugin-transform-react-pug#55]
It seems like Pug transpile its tags directly into `React.createElement(Foo, ...)`-ish function instead of `<Foo>...</Foo>`, that eventually compiles to `React.createElement(_foo, ...)` (but not the full name `Foo`, instead interoped and resolved), and it breaks references to imported files (ReferenceError). I don't know why would this happen. Is anyone having the same issue?

**Comment by ezhlobo** [comment]
@stevefan1999 this plugin transpiles pug into jsx. So `Foo ...` will be `<Foo>...</Foo>`. Then it's usually passed to next plugin `transform-react-jsx`.

It sounds like the problem in your build-flow but I can't say more. Maybe you can provide more details, for example sharing `.babelrc` is a good start.

**Comment by stevefan1999** [comment]
🤔[I made a reproducible repo](https://github.com/stevefan1999/babel-plugin-transform-react-pug-bug).

**Comment by stevefan1999** [comment]
🤔Or perhaps there's something wrong with the TypeScript compiler? I changed tsconfig.json to the following:
```json
{
  "compilerOptions": {
    "jsx": "preserve",
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es2018"
  },
  "exclude": ["node_modules"]
}
```
Then I ran `tsc`, but `App.jsx` is generating this:
```jsx
import * as React from 'react';
import { render } from 'react-dom';
const App = () => pug `
  Foo/
`;
render(<App />, document.getElementById('root'));
```

**Comment by ezhlobo** [comment]
@stevefan1999 thanks for the repo. I'll be able to check that today later but it significantly simplifies everything for me ;).

**Comment by stevefan1999** [comment]
Workaround: 
1. Change `module` to `es2015` or better in `tsconfig.json` so that the actual module resolve strategy is handled by Babel or other tools
2. Either put a comma-list expression or a dummy expression after the import
```tsx
import Foo from './Foo'
Foo
```
Or
```tsx
import Foo from './Foo'; Foo
```
But both of them are ugly workarounds.
