### ISSUE TITLE
Do setup ESLint required to use this plugin ?

### ISSUE THREAD

**Issue by PhmNgocNghia** [pugjs/babel-plugin-transform-react-pug#56]
Error: 
```
./src/App.js
  Line 7:  'pug' is not defined  no-undef

Search for the keywords to learn more about each error.
```

Create-react-app : 1.5.2
Babel-plugin-transform-react-pug: ^6.0.0

**Comment by PhmNgocNghia** [comment]
Nvm after eject and reinstall eslint. Then clear all error by eslint such as : React (unsed-var), fetch/pug (not-defined). It's worked. React docs or babel plugin transform react docs should have mention about if error detect by eslint it won't compile. I leave my repo bellow as reference

**Comment by ezhlobo** [comment]
@PhmNgocNghia hey, we've already mentioned this in the doc: https://github.com/pugjs/babel-plugin-transform-react-pug#eslint-integration

Let me know if it requires more detailed explanation.
