### ISSUE TITLE
Can't figure out how to use locals without quotation marks

### ISSUE THREAD

**Issue by nikita-skobov** [pugjs/babel-plugin-transform-react-pug#59]
I have a function that looks like this:
```
createPanel(obj) {
return pug`
 Card
   CardBody
       CardTitle '{obj.title}'
`
}
```

And that works, but it produces quotation marks around my title, so it shows up as  'My title here', when I just want it to say My title here without the quotes.

I've tried all sorts of various combinations like CardTitle= {obj.title}
CardTitle #{obj.title}
CardTitle= ${obj.title}

and all of those throw errors by either the pug-as-jsx-loader or the pug-lexer

**Comment by ezhlobo** [comment]
@nikita-skobov according to your code snippet and mentioned errors, I think you use [pug-as-jsx-loader](https://github.com/bluewings/pug-as-jsx-loader). I suggest you either create an issue in that repository or use current plugin.
