### ISSUE TITLE
Don't add own keys in static blocks

### ISSUE THREAD

**Issue by ezhlobo** [pugjs/babel-plugin-transform-react-pug#82]
So we basically need to remove keys everywhere where it's possible. Where it is not, then we should wrap by React.Fragment.

### Example

Input:

```pug
if true
  div First
  div Second
```

Actual output:

```jsx
true ? [
  <div key="pug:0:0">First</div>,
  <div key="pug:0:1">Second</div>
] : ...
```

Desired output:

```jsx
true ? [
  <div>First</div>,
  <div>Second</div>
] : ...
```

**Comment by ForbesLindesay** [comment]
In this instance, the desired output is actually:

```js
true ? (
  <React.Fragment>
    <div>First</div>,
    <div>Second</div>
  </React.Fragment>
) : null
```

The only reason I didn't write it that way originally is that `React.Fragment` didn't exist at that point.

**Comment by ezhlobo** [comment]
Done in v7.0.0
