### ISSUE TITLE
pug is not defined when

### ISSUE THREAD

**Issue by EricBeReal** [pugjs/babel-plugin-transform-react-pug#9]
I'm setting up react-router root component using inline pug and receiving a generic "pug is not defined" error using the React.cloneElement function as seen below:
```
import React from 'react';
import SiteHeader from './SiteHeader';
export function GetQuotes(props) {
  return pug`
    .get-quotes
      SiteHeader()
      ${ React.cloneElement(props.children, props) }
   `;
}

export default GetQuotes;
```

Whereas it works just fine using plain old jsx like so:
```
import React from 'react';
import SiteHeader from './SiteHeader';
export function GetQuotes(props) {
  return (
      <div className='get-quotes'>
      <SiteHeader/>
      { React.cloneElement(props.children, props) }
    </div>
  )
}

export default GetQuotes;
```

**Comment by ljbc1994** [comment]
Hi,

If it's a `ReferenceError`, it's because pug hasn't been transpiled into JSX. Have you got a `.babelrc` file as documented in the README?

Otherwise, it could be the ESLint config: see isssue https://github.com/pugjs/babel-plugin-transform-react-pug/issues/7

**Comment by EricBeReal** [comment]
Sorry forgot to mention that, aside from this instance, pug works great in other components in this project.

**Comment by ForbesLindesay** [comment]
Can you submit a failing test case?

**Comment by ForbesLindesay** [comment]
It was probably the interpolation.  Try the latest release, or replace `${ React.cloneElement(props.children, props) }` with `= React.cloneElement(props.children, props)`
