### ISSUE TITLE
 'pug' is not defined no-undef

### ISSUE THREAD

**Issue by passion0470** [pugjs/babel-plugin-transform-react-pug#93]
> Line 39: 'pug' is not defined no-undef

I still get this error. I do not know the cause.

So after that, I did not install eslint and thought there was an error. So I installed enlint.
And if you install eslint, the app will not start
I get this error message from yarn.
>  "eslint": "5.12.0"
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of eslint was detected higher up in the tree:

If you erase and reinstall the eslint,
Line 39: 'pug' is not defined no-undef
I keep getting this error.

I do not know how. Please let me know ..
Please let me know if you have a React + pug sample that works well.
Both react and pug are very sad in my beloved position.

.babelrc

> {
>      "plugins": [
>     "transform-react-pug",
>     "transform-react-jsx"
>   ]
>  }

.eslintrc

> {
>     "plugins": [
>         "react-pug"
>     ],
>     "extends": [
>         "plugin:react-pug/all"
>     ]
> }

package.json

> {
>   "name": "frontend",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "axios": "^0.18.0",
>     "immutable": "^4.0.0-rc.12",
>     "react": "^16.8.2",
>     "react-dom": "^16.8.2",
>     "react-motion": "^0.5.2",
>     "react-redux": "^6.0.0",
>     "react-router-dom": "^4.3.1",
>     "react-scripts": "2.1.5",
>     "react-transition-group": "^2.5.3",
>     "redux": "^4.0.1",
>     "redux-actions": "^2.6.4",
>     "redux-thunk": "^2.3.0",
>     "styled-components": "^4.1.3"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": [
>     ">0.2%",
>     "not dead",
>     "not ie <= 11",
>     "not op_mini all"
>   ],
>   "devDependencies": {
>     "babel-plugin-transform-react-pug": "^7.0.0",
>     "eslint": "^5.14.0",
>     "eslint-plugin-react-pug": "^0.5.7"
>   }
> }

**Comment by ezhlobo** [comment]
@passion0470 I see that you use `react-scripts`, it comes with CRA and it doesn't take into consideration `.babelrc` file. That's not our fall, that is made by CRA and it's intentionally.

You need to have the possibility to modify babel configuration and if you don't want to eject, take into account other options:
https://facebook.github.io/create-react-app/docs/alternatives-to-ejecting

We also have an option with [react-app-rewired](https://github.com/timarney/react-app-rewired#1-injectbabelplugin), check this section in documentation (it might be out of date though):
https://github.com/pugjs/babel-plugin-transform-react-pug#create-react-app

I'm closing the issue but feel free to continue this discussion or re-open it ;).
